function Welcome(){
    document.getElementById("frente").style.display="block";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci1(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="block";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci2(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="block";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci3(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="block";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci4(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="block";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci5(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="block";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci6(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="block";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci7(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="block";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci8(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="block";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci9(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="block"
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci10(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="block";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci11(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="block";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci12(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="block";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci13(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="block";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci14(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="block";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci15(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="block";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci16(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="block";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci17(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="block";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci18(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="block";
    document.getElementById("ejercicio19").style.display="none";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci19(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="block";
    document.getElementById("ejercicio20").style.display="none";

}
function ejerci20(){
    document.getElementById("frente").style.display="none";
    document.getElementById("ejercicio1").style.display="none";
    document.getElementById("ejercicio2").style.display="none";
    document.getElementById("ejercicio3").style.display="none";
    document.getElementById("ejercicio4").style.display="none";
    document.getElementById("ejercicio5").style.display="none";
    document.getElementById("ejercicio6").style.display="none";
    document.getElementById("ejercicio7").style.display="none";
    document.getElementById("ejercicio8").style.display="none";
    document.getElementById("ejercicio9").style.display="none";
    document.getElementById("ejercicio10").style.display="none";
    document.getElementById("ejercicio11").style.display="none";
    document.getElementById("ejercicio12").style.display="none";
    document.getElementById("ejercicio13").style.display="none";
    document.getElementById("ejercicio14").style.display="none";
    document.getElementById("ejercicio15").style.display="none";
    document.getElementById("ejercicio16").style.display="none";
    document.getElementById("ejercicio17").style.display="none";
    document.getElementById("ejercicio18").style.display="none";
    document.getElementById("ejercicio19").style.display="block";
    document.getElementById("ejercicio20").style.display="none";

}